"""empty message

Revision ID: 17675936768a
Revises: 689d61b57474
Create Date: 2024-08-02 17:35:15.515215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17675936768a'
down_revision = '689d61b57474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('start_month',
               existing_type=sa.DATE(),
               type_=sa.String(length=7),
               existing_nullable=False)
        batch_op.alter_column('end_month',
               existing_type=sa.DATE(),
               type_=sa.String(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('end_month',
               existing_type=sa.String(length=7),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('start_month',
               existing_type=sa.String(length=7),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
