"""empty message

Revision ID: 728c3768e890
Revises: 17675936768a
Create Date: 2024-08-05 12:10:13.168624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728c3768e890'
down_revision = '17675936768a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process')
    # ### end Alembic commands ###
