"""empty message

Revision ID: 84a71436904e
Revises: 728c3768e890
Create Date: 2024-08-05 13:42:59.097666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a71436904e'
down_revision = '728c3768e890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('nearest_station', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('experience_years', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('education', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('education')
        batch_op.drop_column('experience_years')
        batch_op.drop_column('nearest_station')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
