"""ind add

Revision ID: a2b2fee0831c
Revises: d54dd574cb79
Create Date: 2024-08-29 14:15:40.944077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b2fee0831c'
down_revision = 'd54dd574cb79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual_development',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_month', sa.String(length=7), nullable=False),
    sa.Column('end_month', sa.String(length=7), nullable=False),
    sa.Column('development_name', sa.String(length=120), nullable=False),
    sa.Column('development_summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('individual_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individual_development_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['individual_development_id'], ['individual_development.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('individual_technology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individual_development_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['individual_development_id'], ['individual_development.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('individual_technology')
    op.drop_table('individual_process')
    op.drop_table('individual_development')
    # ### end Alembic commands ###
